import { createApp } from 'vue';
import App from './App.vue';
import './assets/css/index.css';
import { createPinia } from 'pinia';
import router from './router';
import 'vue-fullpage.js/dist/style.css';
import vueFullpage from 'vue-fullpage.js';
const pinia = createPinia();
const app = createApp(App);
app.use(pinia);
app.use(vueFullpage);
app.use(router).mount('#app');
